const nightPhotosData = [
//Fuji 400
//
{ thumb: 'slrphotos/fuji400nov25-1.thumb.jpg', full: 'slrphotos/fuji400nov25-1.jpg', alt: 'Fuji 400 Photo 1', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-2.thumb.jpg', full: 'slrphotos/fuji400nov25-2.jpg', alt: 'Fuji 400 Photo 2', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-3.thumb.jpg', full: 'slrphotos/fuji400nov25-3.jpg', alt: 'Fuji 400 Photo 3', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-4.thumb.jpg', full: 'slrphotos/fuji400nov25-4.jpg', alt: 'Fuji 400 Photo 4', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-5.thumb.jpg', full: 'slrphotos/fuji400nov25-5.jpg', alt: 'Fuji 400 Photo 5', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-6.thumb.jpg', full: 'slrphotos/fuji400nov25-6.jpg', alt: 'Fuji 400 Photo 6', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-7.thumb.jpg', full: 'slrphotos/fuji400nov25-7.jpg', alt: 'Fuji 400 Photo 7', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-8.thumb.jpg', full: 'slrphotos/fuji400nov25-8.jpg', alt: 'Fuji 400 Photo 8', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-9.thumb.jpg', full: 'slrphotos/fuji400nov25-9.jpg', alt: 'Fuji 400 Photo 9', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-10.thumb.jpg', full: 'slrphotos/fuji400nov25-10.jpg', alt: 'Fuji 400 Photo 10', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-11.thumb.jpg', full: 'slrphotos/fuji400nov25-11.jpg', alt: 'Fuji 400 Photo 11', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-12.thumb.jpg', full: 'slrphotos/fuji400nov25-12.jpg', alt: 'Fuji 400 Photo 12', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-13.thumb.jpg', full: 'slrphotos/fuji400nov25-13.jpg', alt: 'Fuji 400 Photo 13', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-14.thumb.jpg', full: 'slrphotos/fuji400nov25-14.jpg', alt: 'Fuji 400 Photo 14', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-15.thumb.jpg', full: 'slrphotos/fuji400nov25-15.jpg', alt: 'Fuji 400 Photo 15', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-16.thumb.jpg', full: 'slrphotos/fuji400nov25-16.jpg', alt: 'Fuji 400 Photo 16', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-17.thumb.jpg', full: 'slrphotos/fuji400nov25-17.jpg', alt: 'Fuji 400 Photo 17', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },
{ thumb: 'slrphotos/fuji400nov25-18.thumb.jpg', full: 'slrphotos/fuji400nov25-18.jpg', alt: 'Fuji 400 Photo 18', caption: 'Shot on Fuji 400 with my Canon Rebel 2000' },

//Bunnygoat Geminid shower and others 
{ thumb: 'slrphotos/Porta400Geminid-1.thumb.jpg', full: 'slrphotos/Porta400Geminid-1.jpg', alt: 'Porta 400 Geminid Photo', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/Porta400Geminid (1 of 15).thumb.jpg', full: 'slrphotos/Porta400Geminid (1 of 15).jpg', alt: 'Porta 400 Geminid Photo 1', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/Porta400Geminid (3 of 15).thumb.jpg', full: 'slrphotos/Porta400Geminid (3 of 15).jpg', alt: 'Porta 400 Geminid Photo 3', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/Porta400Geminid (2 of 15).thumb.jpg', full: 'slrphotos/Porta400Geminid (2 of 15).jpg', alt: 'Porta 400 Geminid Photo 2', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/Porta400Geminid (4 of 15).thumb.jpg', full: 'slrphotos/Porta400Geminid (4 of 15).jpg', alt: 'Porta 400 Geminid Photo 4', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/Porta400Geminid (5 of 15).thumb.jpg', full: 'slrphotos/Porta400Geminid (5 of 15).jpg', alt: 'Porta 400 Geminid Photo 5', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/Porta400Geminid (6 of 15).thumb.jpg', full: 'slrphotos/Porta400Geminid (6 of 15).jpg', alt: 'Porta 400 Geminid Photo 6', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/Porta400Geminid (8 of 15).thumb.jpg', full: 'slrphotos/Porta400Geminid (8 of 15).jpg', alt: 'Porta 400 Geminid Photo 8', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/Porta400Geminid (9 of 15).thumb.jpg', full: 'slrphotos/Porta400Geminid (9 of 15).jpg', alt: 'Porta 400 Geminid Photo 9', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/Porta400Geminid (10 of 15).thumb.jpg', full: 'slrphotos/Porta400Geminid (10 of 15).jpg', alt: 'Porta 400 Geminid Photo 10', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/Porta400Geminid (13 of 15).thumb.jpg', full: 'slrphotos/Porta400Geminid (13 of 15).jpg', alt: 'Porta 400 Geminid Photo 13', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/Porta400Geminid (14 of 15).thumb.jpg', full: 'slrphotos/Porta400Geminid (14 of 15).jpg', alt: 'Porta 400 Geminid Photo 14', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/Porta400Geminid (15 of 15).thumb.jpg', full: 'slrphotos/Porta400Geminid (15 of 15).jpg', alt: 'Porta 400 Geminid Photo 15', caption: 'Shot with Porta 400' },
{ thumb: 'slrphotos/kodakgold200night-1.thumb.jpg', full: 'slrphotos/kodakgold200night-1.jpg', alt: 'Kodak Gold 200 Night Photo 1', caption: 'Shot with Kodak Gold 200' },
{ thumb: 'slrphotos/kodakgold200night-2.thumb.jpg', full: 'slrphotos/kodakgold200night-2.jpg', alt: 'Kodak Gold 200 Night Photo 2', caption: 'Shot with Kodak Gold 200' },
{ thumb: 'slrphotos/kodakgold200night-3.thumb.jpg', full: 'slrphotos/kodakgold200night-3.jpg', alt: 'Kodak Gold 200 Night Photo 3', caption: 'Shot with Kodak Gold 200' },
{ thumb: 'slrphotos/kodakgold200night-4.thumb.jpg', full: 'slrphotos/kodakgold200night-4.jpg', alt: 'Kodak Gold 200 Night Photo 4', caption: 'Shot with Kodak Gold 200' },
{ thumb: 'slrphotos/Fuji400nov25-1.thumb.jpg', full: 'slrphotos/Fuji400nov25-1.jpg', alt: 'Fuji 400 Nov 25 Photo 1', caption: 'Shot with Fuji 400' },
{ thumb: 'slrphotos/Fuji400nov25-2.thumb.jpg', full: 'slrphotos/Fuji400nov25-2.jpg', alt: 'Fuji 400 Nov 25 Photo 2', caption: 'Shot with Fuji 400' },
{ thumb: 'slrphotos/Fuji400nov25-3.thumb.jpg', full: 'slrphotos/Fuji400nov25-3.jpg', alt: 'Fuji 400 Nov 25 Photo 3', caption: 'Shot with Fuji 400' },
//Bunny Goat Farm first night out
{ thumb: 'slrphotos/bunnygoat001.thumb.jpg', full: 'slrphotos/bunnygoat001.jpg', alt: 'Kodacolor 100 Photo 1', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat002.thumb.jpg', full: 'slrphotos/bunnygoat002.jpg', alt: 'Kodacolor 100 Photo 2', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat003.thumb.jpg', full: 'slrphotos/bunnygoat003.jpg', alt: 'Kodacolor 100 Photo 3', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat004.thumb.jpg', full: 'slrphotos/bunnygoat004.jpg', alt: 'Kodacolor 100 Photo 4', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat005.thumb.jpg', full: 'slrphotos/bunnygoat005.jpg', alt: 'Kodacolor 100 Photo 5', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat006.thumb.jpg', full: 'slrphotos/bunnygoat006.jpg', alt: 'Kodacolor 100 Photo 6', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat007.thumb.jpg', full: 'slrphotos/bunnygoat007.jpg', alt: 'Kodacolor 100 Photo 7', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat008.thumb.jpg', full: 'slrphotos/bunnygoat008.jpg', alt: 'Kodacolor 100 Photo 8', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat009.thumb.jpg', full: 'slrphotos/bunnygoat009.jpg', alt: 'Kodacolor 100 Photo 9', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat010.thumb.jpg', full: 'slrphotos/bunnygoat010.jpg', alt: 'Kodacolor 100 Photo 10', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat016.thumb.jpg', full: 'slrphotos/bunnygoat016.jpg', alt: 'Kodacolor 100 Photo 16', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat017.thumb.jpg', full: 'slrphotos/bunnygoat017.jpg', alt: 'Kodacolor 100 Photo 17', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat018.thumb.jpg', full: 'slrphotos/bunnygoat018.jpg', alt: 'Kodacolor 100 Photo 18', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat019.thumb.jpg', full: 'slrphotos/bunnygoat019.jpg', alt: 'Kodacolor 100 Photo 19', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat020.thumb.jpg', full: 'slrphotos/bunnygoat020.jpg', alt: 'Kodacolor 100 Photo 20', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat021.thumb.jpg', full: 'slrphotos/bunnygoat021.jpg', alt: 'Kodacolor 100 Photo 21', caption: 'Kodacolor 100' },
{ thumb: 'slrphotos/bunnygoat022.thumb.jpg', full: 'slrphotos/bunnygoat022.jpg', alt: 'Kodacolor 100 Photo 22', caption: 'Kodacolor 100' },
//Lomography Turquoise
{ thumb: 'slrphotos/lomogturqno1013.thumb.jpg', full: 'slrphotos/lomogturqno1013.jpg', alt: 'Lomography Turquoise Photo 13', caption: 'Shot with Lomography Turquoise at 250 ISO though my Canon Rebel 2000' },
{ thumb: 'slrphotos/lomogturqno1014.thumb.jpg', full: 'slrphotos/lomogturqno1014.jpg', alt: 'Lomography Turquoise Photo 14', caption: 'Shot with Lomography Turquoise at 250 ISO though my Canon Rebel 2000' },
{ thumb: 'slrphotos/lomogturqno1015.thumb.jpg', full: 'slrphotos/lomogturqno1015.jpg', alt: 'Lomography Turquoise Photo 15', caption: 'Shot with Lomography Turquoise at 250 ISO though my Canon Rebel 2000' },
{ thumb: 'slrphotos/lomogturqno1016.thumb.jpg', full: 'slrphotos/lomogturqno1016.jpg', alt: 'Lomography Turquoise Photo 16', caption: 'Shot with Lomography Turquoise at 250 ISO though my Canon Rebel 2000' },
{ thumb: 'slrphotos/lomogturqno1017.thumb.jpg', full: 'slrphotos/lomogturqno1017.jpg', alt: 'Lomography Turquoise Photo 17', caption: 'Shot with Lomography Turquoise at 250 ISO though my Canon Rebel 2000' },

// Vallejo at night in November with fuji400
{ thumb: 'slrphotos/vallejo.night.nov25.fuji400.001.thumb.jpg', full: 'slrphotos/vallejo.night.nov25.fuji400.001.jpg', alt: 'Vallejo Night Fuji400 Photo 1', caption: 'Shot in November of 2025, with Fuji400, I had no idea how cool the street light was going to be!' },
{ thumb: 'slrphotos/vallejo.night.nov25.fuji400.002.thumb.jpg', full: 'slrphotos/vallejo.night.nov25.fuji400.002.jpg', alt: 'Vallejo Night Fuji400 Photo 2', caption: 'Shot in November of 2025, with Fuji400, I wonder what kind of game they play there.' },
{ thumb: 'slrphotos/vallejo.night.nov25.fuji400.004.thumb.jpg', full: 'slrphotos/vallejo.night.nov25.fuji400.004.jpg', alt: 'Vallejo Night Fuji400 Photo 4', caption: 'Shot in November of 2025, with Fuji400, this was absolutely a mistake and I\'m all for it! It looks like an oil painting!' },
{ thumb: 'slrphotos/vallejo.night.nov25.fuji400.006.thumb.jpg', full: 'slrphotos/vallejo.night.nov25.fuji400.006.jpg', alt: 'Vallejo Night Fuji400 Photo 5', caption: 'Shot in November of 2025, with Fuji400, while a bad astrophotography shot, it\'s still pretty to me!' },
{ thumb: 'slrphotos/vallejo.night.nov25.fuji400.003.thumb.jpg', full: 'slrphotos/vallejo.night.nov25.fuji400.003.jpg', alt: 'Vallejo Night Fuji400 Photo 8', caption: 'Shot in November of 2025, with Fuji400, I love the still water reflecting the firmament.' },
{ thumb: 'slrphotos/vallejo.night.nov25.fuji400.009.thumb.jpg', full: 'slrphotos/vallejo.night.nov25.fuji400.009.jpg', alt: 'Vallejo Night Fuji400 Photo 9', caption: 'Shot in November of 2025, with Fuji400, pretty orange.' },
{ thumb: 'slrphotos/vallejo.night.nov25.fuji400.010.thumb.jpg', full: 'slrphotos/vallejo.night.nov25.fuji400.010.jpg', alt: 'Vallejo Night Fuji400 Photo 10', caption: 'Shot in November of 2025, with Fuji400, I\'m gonna have to go and get this shot again! But this is still nice.' },
{ thumb: 'slrphotos/vallejo.night.nov25.fuji400.011.thumb.jpg', full: 'slrphotos/vallejo.night.nov25.fuji400.011.jpg', alt: 'Vallejo Night Fuji400 Photo 11', caption: 'Shot in November of 2025, with Fuji400, I love these kinda shots, they\'re like a box of chocolates!' },
{ thumb: 'slrphotos/vallejo.night.nov25.fuji400.012.thumb.jpg', full: 'slrphotos/vallejo.night.nov25.fuji400.012.jpg', alt: 'Vallejo Night Fuji400 Photo 12', caption: 'Shot in November of 2025, with Fuji400, this one\'s got something to it that I want to try and capture more of!' },
// HansPark Astro 
{ thumb: 'slrphotos/kgold200astro.001.thumb.jpg', full: 'slrphotos/kgold200astro.001.jpg', alt: 'Kodak Gold 200 Astro Photo 1', caption: 'I\'m glad I stopped to take this one. Kodak Gold 200' },
{ thumb: 'slrphotos/kgold200astro.002.thumb.jpg', full: 'slrphotos/kgold200astro.002.jpg', alt: 'Kodak Gold 200 Astro Photo 2', caption: 'This was a fun night to shoot. I am happy with the results also! Kodak Gold 200, 10 to 30 second exposure' },
{ thumb: 'slrphotos/kgold200astro.003.thumb.jpg', full: 'slrphotos/kgold200astro.003.jpg', alt: 'Kodak Gold 200 Astro Photo 3', caption: 'I forgot the attachment for my tripod, so I improvised and was glad I did! Kodak Gold 200, 10 to 30 second exposure' },
{ thumb: 'slrphotos/kgold200astro.004.thumb.jpg', full: 'slrphotos/kgold200astro.004.jpg', alt: 'Kodak Gold 200 Astro Photo 4', caption: 'Im gonna have to remember to shoot more from the ground like this. Kodak Gold 200, 10 to 30 second exposure' },
{ thumb: 'slrphotos/kgold200astro.005.thumb.jpg', full: 'slrphotos/kgold200astro.005.jpg', alt: 'Kodak Gold 200 Astro Photo 5', caption: 'Pretty colors. Kodak Gold 200, 10 to 30 second exposure' },
{ thumb: 'slrphotos/kgold200astro.006.thumb.jpg', full: 'slrphotos/kgold200astro.006.jpg', alt: 'Kodak Gold 200 Astro Photo 6', caption: 'I am unsure which I liked more, and so uploaded both. Kodak Gold 200, 10 to 30 second exposure' },
{ thumb: 'slrphotos/kgold200astro.007.thumb.jpg', full: 'slrphotos/kgold200astro.007.jpg', alt: 'Kodak Gold 200 Astro Photo 7', caption: 'Nothing special, I like these types of shots though. Kodak Gold 200, 10 to 30 second exposure' },

// Lake Herman Oct.'25 
{ thumb: 'slrphotos/lakeherm.kodak400007.thumb.jpg', full: 'slrphotos/lakeherm.kodak400007.jpg', alt: 'Kodak GC 400 Photo 7', caption: 'Canon Rebel 2000 using Kodak GC 400 and shot through a Canon EF 50mm f/1.8' },
{ thumb: 'slrphotos/lakeherm.kodak400005.thumb.jpg', full: 'slrphotos/lakeherm.kodak400005.jpg', alt: 'Kodak GC 400 Photo 5', caption: 'Canon Rebel 2000 using Kodak GC 400 and shot through a Canon EF 50mm f/1.8' },
{ thumb: 'slrphotos/lakeherm.kodak400004.thumb.jpg', full: 'slrphotos/lakeherm.kodak400004.jpg', alt: 'Kodak GC 400 Photo 4', caption: 'Canon Rebel 2000 using Kodak GC 400 and shot through a Canon EF 50mm f/1.8' },
{ thumb: 'slrphotos/lakeherm.kodak400001.thumb.jpg', full: 'slrphotos/lakeherm.kodak400001.jpg', alt: 'Kodak GC 400 Photo 1', caption: 'Canon Rebel 2000 using Kodak GC 400 and shot through a Canon EF 50mm f/1.8' },
{ thumb: 'slrphotos/lakeherm.kodak400006.thumb.jpg', full: 'slrphotos/lakeherm.kodak400006.jpg', alt: 'Kodak GC 400 Photo 6', caption: 'Canon Rebel 2000 using Kodak GC 400 and shot through a Canon EF 50mm f/1.8' },
{ thumb: 'slrphotos/oct25.lakeh.k400006.thumb.jpg', full: 'slrphotos/oct25.lakeh.k400006.jpg', alt: 'Kodak GC 400 Photo 6', caption: 'Canon Rebel 2000 using Kodak GC 400 and shot through a Canon EF 50mm f/1.8' },
   // Random
   { thumb: 'Aurora800.001.thumb.jpg', full: 'Aurora800.001.jpg', alt: 'Aurora800', caption: 'So apperently I shot this with Auroroa800. I stumbled upon this photo that was shot back in April. I have so many shots that I initially pass on, but when coming back  I realize they have something neat within them that I missed.  I love film.. so cool.' },
   // RFO September 
    { thumb: 'slrphotos/porta800aug014.thumb.jpg', full: 'slrphotos/porta800aug014.jpg', alt: 'Porta 800 Photo 14', caption: 'Portra 800 - So far, this is the longest exposure I have done at 7 minutes! 28mm at F/3.5, Cygnus, or the Cygnus cluster, should be up there somewhere.' },
    { thumb: 'slrphotos/porta800aug009.thumb.jpg', full: 'slrphotos/porta800aug009.jpg', alt: 'Porta 800 Photo 9', caption: 'Portra 800 - I like how the nearby sodium lamps tinted the sky' },
    { thumb: 'slrphotos/porta800aug011.thumb.jpg', full: 'slrphotos/porta800aug011.jpg', alt: 'Porta 800 Photo 11', caption: 'Portra 800 - Aquila, 28mm at F/3.5 with a 4 minute exposure' },
    { thumb: 'slrphotos/porta800aug012.thumb.jpg', full: 'slrphotos/porta800aug012.jpg', alt: 'Porta 800 Photo 12', caption: 'Portra 800 - The observatory I have opportunities to attend star parties at, good stuff!' },
    { thumb: 'slrphotos/porta800aug013.thumb.jpg', full: 'slrphotos/porta800aug013.jpg', alt: 'Porta 800 Photo 13', caption: 'Portra 800 - My notes say that the constellation Deneb is in the top right of the photograph, but I\'m more pleased with the plane! (I remember staring up during the exposure and hoping I would get this shot)' },
    { thumb: 'slrphotos/porta800aug015.thumb.jpg', full: 'slrphotos/porta800aug015.jpg', alt: 'Porta 800 Photo 15', caption: 'Portra 800 - Perseus+Andromeda, 28mm F3.5 for 3 minutes. At these star party events, only red light is allowed, I forgot I had my headlamp turned on for the first minute or so of this exposure, but since I was just staring at the sky myself, it helped the photo.' },
    { thumb: 'slrphotos/porta800aug016.thumb.jpg', full: 'slrphotos/porta800aug016.jpg', alt: 'Porta 800 Photo 16', caption: 'Portra 800 - 28mm F/3.5 for 5 minutes of exposure time. Aquarius should be up there somewhere, I\'m going to keep shooting astro with Kodak\'s Portra 800, These came out great!' },
    { thumb: 'slrphotos/porta800aug010.thumb.jpg', full: 'slrphotos/porta800aug010.jpg', alt: 'Porta 800 Photo 10', caption: 'Portra 800 - Stopped on my way back from the Observatory to take some shots of this place. One of the reasons I love film, is that I had forgotten I took a pic whilst a car was driving by, and was pleasantly surprised once I saw this one' },
    // CineStill 800T fireworks photos
    { thumb: 'slrphotos/Cinstill800t.002.thumb.jpg', full: 'slrphotos/Cinstill800t.002.jpg', alt: 'CineStill 800T Photo 2', caption: 'CineStill 800T, July 4th, 25. that is 9 out of 10 of those are "privately owned" fireworks, hahaa!' },
    { thumb: 'slrphotos/Cinstill800t.003.thumb.jpg', full: 'slrphotos/Cinstill800t.003.jpg', alt: 'CineStill 800T Photo 3', caption: 'CineStill 800T, July 4th, 25. that is 9 out of 10 of those are "privately owned" fireworks, hahaa! The firefighters where busy that night.' },
    { thumb: 'slrphotos/Cinstill800t.004.thumb.jpg', full: 'slrphotos/Cinstill800t.004.jpg', alt: 'CineStill 800T Photo 4', caption: 'CineStill 800T, July 4th, 25. that is 9 out of 10 of those are "privately owned" fireworks, hahaa!' },
    { thumb: 'slrphotos/Cinstill800t.005.thumb.jpg', full: 'slrphotos/Cinstill800t.005.jpg', alt: 'CineStill 800T Photo 5', caption: 'CineStill 800T, July 4th, 25. that is 9 out of 10 of those are "privately owned" fireworks, hahaa!' },
    { thumb: 'slrphotos/Kporta160.001.thumb.jpg', full: 'slrphotos/Kporta160.001.jpg', alt: 'fluffy trees', caption: 'Kodak porta 160! while I wont be sharing the photos I took of my family on the rest of the roll, they look... 160 looks like it would feel soft.. if that makes sense, apt that these trees look so fluffy after a 30 second exposure!' }, 
    // NEW Yosemite photos - FIRST (excluding 006, 009, 010 which go to general)
    { thumb: 'slrphotos/Yosme001.thumb.jpg', full: 'slrphotos/Yosme001.jpg', alt: 'Yosemite Photo 1', caption: 'Cinestill 800T surprised me (not in a good way!) but I think campfire smoke during these long exposures was the real issue. Great learning moment, and I got some neat photos anyway!' },
    { thumb: 'slrphotos/Yosme002.thumb.jpg', full: 'slrphotos/Yosme002.jpg', alt: 'Yosemite Photo 2', caption: "Cinestill 800T, I'm going to have to try again but without the campfires!" },
    { thumb: 'slrphotos/n1yose007.thumb.jpg', full: 'slrphotos/n1yose007.jpg', alt: 'Night Yosemite Photo 7', caption: "Cinestill 800T, I'm waiting for a chance to do some truly long exposures, I'm curious how this stuff will hold up." },
    { thumb: 'slrphotos/Yosme004.thumb.jpg', full: 'slrphotos/Yosme004.jpg', alt: 'Yosemite Photo 4', caption: 'Kodak Ultramax 400 was king this trip' },
    { thumb: 'slrphotos/Yosme005.thumb.jpg', full: 'slrphotos/Yosme005.jpg', alt: 'Yosemite Photo 5', caption: 'Kodak Ultramax 400 handling >15 seconds perfectly' },
    { thumb: 'slrphotos/Yosme007.thumb.jpg', full: 'slrphotos/Yosme007.jpg', alt: 'Yosemite Photo 7', caption: 'Harman Red 125 pushed to 250' },
    { thumb: 'slrphotos/Yosme008.thumb.jpg', full: 'slrphotos/Yosme008.jpg', alt: 'Yosemite Photo 8', caption: 'Harman Red 125 pushed to 250, I love seeing what will come of the shots I take with this film.' },
    { thumb: 'slrphotos/Yosme011.thumb.jpg', full: 'slrphotos/Yosme011.jpg', alt: 'Yosemite Photo 11', caption: 'Harman Red 125 pushed to 250, So far I have had the most success with this film!' },
    { thumb: 'slrphotos/Yosme012.thumb.jpg', full: 'slrphotos/Yosme012.jpg', alt: 'Yosemite Photo 12', caption: "Harman Red 125 pushed to 250, When getting these photos ready to publish, I don't adjust the color or try to make any adjustments really, at all, with Harman Red" },
    { thumb: 'slrphotos/Yosme013.thumb.jpg', full: 'slrphotos/Yosme013.jpg', alt: 'Yosemite Photo 13', caption: "Harman Red 125 pushed to 250, The tone is simply the chemicals doing their thing! I'll bump up the blacks a bit, or fix the exposure, but I don't have to often! very surprising!" },
    { thumb: 'slrphotos/Yosme014.thumb.jpg', full: 'slrphotos/Yosme014.jpg', alt: 'Yosemite Photo 14', caption: 'Harman Red 125 pushed to 250, Happy Accident with this shot' },

    // KG Photos
    { thumb: 'slrphotos/KG002.thumb.jpg', full: 'slrphotos/KG002.jpg', alt: 'KG Photo 2', caption: 'Kodak Ultramax 400, this stuff handled much better than I was expecting, once again I learned something!' },
    { thumb: 'slrphotos/KG005.thumb.jpg', full: 'slrphotos/KG005.jpg', alt: 'KG Photo 5', caption: "Kodak Ultramax 400 proved that if something's not broke.." },
    // n1yose photos
    { thumb: 'slrphotos/n1yose001.thumb.jpg', full: 'slrphotos/n1yose001.jpg', alt: 'Night Yosemite Photo 1', caption: 'Cinestill 800T surprised me (not in a good way!) but I think campfire smoke during these long exposures was the real issue. Great learning moment, and I got some neat photos anyway!' },
    { thumb: 'slrphotos/n1yose002.thumb.jpg', full: 'slrphotos/n1yose002.jpg', alt: 'Night Yosemite Photo 2', caption: 'Cinestill 800T surprised me (not in a good way!) but I think campfire smoke during these long exposures was the real issue. Great learning moment, and I got some neat photos anyway!' },
    { thumb: 'slrphotos/n1yose003.thumb.jpg', full: 'slrphotos/n1yose003.jpg', alt: 'Night Yosemite Photo 3', caption: 'Cinestill 800T surprised me (not in a good way!) but I think campfire smoke during these long exposures was the real issue. Great learning moment, and I got some neat photos anyway!' },
    { thumb: 'slrphotos/n1yose004.thumb.jpg', full: 'slrphotos/n1yose004.jpg', alt: 'Night Yosemite Photo 4', caption: 'Cinestill 800T surprised me (not in a good way!) but I think campfire smoke during these long exposures was the real issue. Great learning moment, and I got some neat photos anyway!' },
    { thumb: 'slrphotos/n1yose005.thumb.jpg', full: 'slrphotos/n1yose005.jpg', alt: 'Night Yosemite Photo 5', caption: 'Cinestill 800T surprised me (not in a good way!) but I think campfire smoke during these long exposures was the real issue. Great learning moment, and I got some neat photos anyway!' },
    { thumb: 'slrphotos/n1yose006.thumb.jpg', full: 'slrphotos/n1yose006.jpg', alt: 'Night Yosemite Photo 6', caption: 'Cinestill 800T surprised me (not in a good way!) but I think campfire smoke during these long exposures was the real issue. Great learning moment, and I got some neat photos anyway!' },
    { thumb: 'slrphotos/n1yose008.thumb.jpg', full: 'slrphotos/n1yose008.jpg', alt: 'Night Yosemite Photo 8', caption: 'Cinestill 800T surprised me (not in a good way!) but I think campfire smoke during these long exposures was the real issue. Great learning moment, and I got some neat photos anyway!' },
    
    // MayCFO photos
    { thumb: 'slrphotos/MayCFO002.thumb.jpg', full: 'slrphotos/MayCFO002.jpg', alt: 'May CFO Photo 2', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO<br>Exposure: 1/60 (I believe)' },
    { thumb: 'slrphotos/MayCFO003.thumb.jpg', full: 'slrphotos/MayCFO003.jpg', alt: 'May CFO Photo 3', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO<br>Exposure: 30 seconds' },
    { thumb: 'slrphotos/MayCFO004.thumb.jpg', full: 'slrphotos/MayCFO004.jpg', alt: 'May CFO Photo 4', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO' },
    { thumb: 'slrphotos/MayCFO005.thumb.jpg', full: 'slrphotos/MayCFO005.jpg', alt: 'May CFO Photo 5', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO' },
    { thumb: 'slrphotos/MayCFO006.thumb.jpg', full: 'slrphotos/MayCFO006.jpg', alt: 'May CFO Photo 6', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO' },
    { thumb: 'slrphotos/MayCFO007.thumb.jpg', full: 'slrphotos/MayCFO007.jpg', alt: 'May CFO Photo 7', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO' },
    { thumb: 'slrphotos/MayCFO008.thumb.jpg', full: 'slrphotos/MayCFO008.jpg', alt: 'May CFO Photo 8', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO' },
    { thumb: 'slrphotos/MayCFO010.thumb.jpg', full: 'slrphotos/MayCFO010.jpg', alt: 'May CFO Photo 10', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO' },
    { thumb: 'slrphotos/MayCFO009.thumb.jpg', full: 'slrphotos/MayCFO009.jpg', alt: 'May CFO Photo 9', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO' },
    { thumb: 'slrphotos/MayCFO013.thumb.jpg', full: 'slrphotos/MayCFO013.jpg', alt: 'May CFO Photo 13', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO<br>Exposure: 40 seconds' },
    { thumb: 'slrphotos/MayCFO012.thumb.jpg', full: 'slrphotos/MayCFO012.jpg', alt: 'May CFO Photo 12', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO<br>Exposure: 90 seconds' },
    { thumb: 'slrphotos/MayCFO011.thumb.jpg', full: 'slrphotos/MayCFO011.jpg', alt: 'May CFO Photo 11', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO<br>Exposure: 240 seconds!' },
    { thumb: 'slrphotos/MayCFO014.thumb.jpg', full: 'slrphotos/MayCFO014.jpg', alt: 'May CFO Photo 14', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO' },
    { thumb: 'slrphotos/MayCFO015.thumb.jpg', full: 'slrphotos/MayCFO015.jpg', alt: 'May CFO Photo 15', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO<br>This shot is the longest exposure I\'ve done so far, at around 5 minutes! Its good to know My star tracker works' },
    { thumb: 'slrphotos/MayCFO016.thumb.jpg', full: 'slrphotos/MayCFO016.jpg', alt: 'May CFO Photo 16', caption: 'Ektachrome 100 E100 Color reversal film, Pushed +2 to 400 ISO' },
    
    // Friday photos
    { thumb: 'slrphotos/Friday001.thumb.jpg', full: 'slrphotos/Friday001.jpg', alt: 'Night Photo 1', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Friday002.thumb.jpg', full: 'slrphotos/Friday002.jpg', alt: 'Night Photo 2', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Tests006.thumb.jpg', full: 'slrphotos/Tests006.jpg', alt: 'Film Photo 6', caption: '35mm film test shot' },
    { thumb: 'slrphotos/Friday006.thumb.jpg', full: 'slrphotos/Friday006.jpg', alt: 'Night Photo 6', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Friday007.thumb.jpg', full: 'slrphotos/Friday007.jpg', alt: 'Night Photo 7', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Tests007.thumb.jpg', full: 'slrphotos/Tests007.jpg', alt: 'Film Photo 7', caption: '35mm film test shot' },
    { thumb: 'slrphotos/Friday014.thumb.jpg', full: 'slrphotos/Friday014.jpg', alt: 'Night Photo 14', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Friday015.thumb.jpg', full: 'slrphotos/Friday015.jpg', alt: 'Night Photo 15', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Friday016.thumb.jpg', full: 'slrphotos/Friday016.jpg', alt: 'Night Photo 16', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Friday017.thumb.jpg', full: 'slrphotos/Friday017.jpg', alt: 'Night Photo 17', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Friday018.thumb.jpg', full: 'slrphotos/Friday018.jpg', alt: 'Night Photo 18', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Friday019.thumb.jpg', full: 'slrphotos/Friday019.jpg', alt: 'Night Photo 19', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Friday020.thumb.jpg', full: 'slrphotos/Friday020.jpg', alt: 'Night Photo 20', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Friday021.thumb.jpg', full: 'slrphotos/Friday021.jpg', alt: 'Night Photo 21', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Friday022.thumb.jpg', full: 'slrphotos/Friday022.jpg', alt: 'Night Photo 22', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Friday023.thumb.jpg', full: 'slrphotos/Friday023.jpg', alt: 'Night Photo 23', caption: 'Night photography with Canon Rebel 2000' },
    { thumb: 'slrphotos/Tests001.thumb.jpg', full: 'slrphotos/Tests001.jpg', alt: 'Film Photo 1', caption: '35mm film test shot' }
];
